### ISSUE TITLE
Bug: 输入“今日词云”后报错

### ISSUE THREAD

**Issue by AirKeen76** [he0119/nonebot-plugin-wordcloud#148]
[PyBot][01:47:42.409][INFO] [message] 触发 Matcher(type='message', module=nonebot_plugin_wordcloud)
[PyBot][01:47:42.409][ERROR] [message]Running Matcher(type='message', module=nonebot_plugin_wordcloud) failed.
Traceback (most recent call last):
  File "D:\AK76\Yunzai-bot\plugins\py-plugin\main.py", line 17, in <module>
    yunzai_nonebot.run()
  File "D:\AK76\Yunzai-bot\plugins\py-plugin\yunzai_nonebot\__init__.py", line 30, in run
    nonebot.run(*args, **kwargs)
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\AK76\Yunzai-bot\plugins\py-plugin\yunzai_nonebot\hijack\driver.py", line 42, in run
    loop.run_until_complete(self.serve())
  File "D:\AK76\Python\3.10\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "D:\AK76\Python\3.10\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\AK76\Python\3.10\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "D:\AK76\Python\3.10\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "D:\AK76\Python\3.10\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot_plugin_wordcloud\__init__.py", line 224, in handle_get_messages_group_message
    state["messages"] = await get_messages_plain_text(
  File "C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-IiUm2lfJ-py3.10\lib\site-packages\nonebot_plugin_chatrecorder\record.py", line 138, in get_messages_plain_text
    whereclause = filter_statement(**kwargs)
TypeError: filter_statement() got an unexpected keyword argument 'user_ids'

**Comment by he0119** [comment]
你的 chatrecorder 版本是 0.3 以下吗？

**Comment by AirKeen76** [comment]
是从github下载的最新版的

**Comment by he0119** [comment]
> 是从github下载的最新版的

请使用 0.2.4 版本，词云并没有适配最新版的 chatrecorder。

**Comment by AirKeen76** [comment]
更换0.2.4之后机器人无法启动
08-09 10:04:33 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\base.py", line 246, in _catch_revision_errors
    yield
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\base.py", line 456, in _upgrade_revs
    for script in reversed(list(revs))
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 797, in iterate_revisions
    revisions, heads = fn(
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 1452, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 525, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 525, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 550, in get_revisions
    return tuple(
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 551, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\revision.py", line 622, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '44cce443d2c0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\AK76\Python\3.10\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_datastore\db.py", line 104, in init_db
    await upgrade(config, "head")
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_datastore\script\command.py", line 245, in upgrade
    await run_migration()
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_datastore\script\utils.py", line 123, in run_migration
    await connection.run_sync(do_run_migrations, plugin_name)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 841, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 194, in greenlet_spawn
    result = context.switch(value)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_datastore\script\utils.py", line 115, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\runtime\environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\runtime\migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_datastore\script\command.py", line 234, in upgrade
    return script._upgrade_revs(revision, rev)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\base.py", line 444, in _upgrade_revs
    with self._catch_revision_errors(
  File "D:\AK76\Python\3.10\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Air\LittlePaimon\.venv\lib\site-packages\alembic\script\base.py", line 278, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '44cce443d2c0'

**Comment by he0119** [comment]
你需要把老数据库删掉。

**Comment by AirKeen76** [comment]
删了之后可以用了，谢谢喵，之前一直不知道怎么找旧的数据库在哪。
