### ISSUE TITLE
Bug: 出现异常,定时发送词云无法正常发送

### ISSUE THREAD

**Issue by axlmly** [he0119/nonebot-plugin-wordcloud#254]
### wordcloud 版本

0.7.0

### chatrecorder 版本

0.6.0

### saa 版本

0.6.0

### alconna 版本

0.38.2

### 描述问题

使用 开启词云每日定时发送 失败并报错

使用的并不是gocq的onebot,而是云仔的ws插件加上ntqq不知道有没有影响

### 复现步骤

开启词云每日定时发送 然后等

### 期望的结果

定时任务正常发送

### 截图或日志

03-04 01:10:00 [INFO] nonebot_plugin_wordcloud | 开始发送每日词云，时间为 17:10:00
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\xiuzh\AppData\Local\Temp\jieba.cache
Loading model cost 1.096 seconds.
Prefix dict has been built successfully.
03-04 01:10:06 [ERROR] apscheduler | Job "Scheduler.run_task (trigger: cron[hour='1', minute='10', second='0'], next run at: 2024-03-05 01:10:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\BOT\nonebot\axlmly-bot\bot.py", line 19, in <module>
    nonebot.run()
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xiuzh\.conda\envs\nonebot\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\xiuzh\.conda\envs\nonebot\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\xiuzh\.conda\envs\nonebot\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\xiuzh\.conda\envs\nonebot\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\xiuzh\.conda\envs\nonebot\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\xiuzh\.conda\envs\nonebot\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\nonebot_plugin_wordcloud\schedule.py", line 108, in run_task
    await saa.Image(image).send_to(target)
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\nonebot_plugin_saa\abstract_factories.py", line 205, in send_to
    return await MessageFactory(self).send_to(target, bot)
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\nonebot_plugin_saa\abstract_factories.py", line 409, in send_to
    bot = get_bot(target)
  File "E:\BOT\nonebot\axlmly-bot\.venv\Lib\site-packages\nonebot_plugin_saa\auto_select_bot.py", line 129, in get_bot
    raise NoBotFound()
nonebot_plugin_saa.utils.exceptions.NoBotFound

![image](https://github.com/he0119/nonebot-plugin-wordcloud/assets/41771421/17cffb67-17d0-47a1-aa11-01fb8683e38b)

**Comment by he0119** [comment]
看起来是没能找到对应的 Bot，你试试重启一下，看看 saa 有没有正确获取到群组列表呢？

**Comment by axlmly** [comment]
> 看起来是没能找到对应的 Bot，你试试重启一下，看看 saa 有没有正确获取到群组列表呢？

尝试过重启,但还是同样的报错.
怎么检查saa有没有正确获取群组列表呢?
![f326f7cb2148ec3c11b8337d7e533415](https://github.com/he0119/nonebot-plugin-wordcloud/assets/41771421/2aa8d4ae-ad4f-4c61-a8ad-12cfc0de72c6)
![image](https://github.com/he0119/nonebot-plugin-wordcloud/assets/41771421/b238c543-a6c0-4487-bf76-a8398895f389)

**Comment by he0119** [comment]
> > 看起来是没能找到对应的 Bot，你试试重启一下，看看 saa 有没有正确获取到群组列表呢？
> 
> 尝试过重启,但还是同样的报错. 怎么检查saa有没有正确获取群组列表呢?

你可以将 LOG_LEVEL 设置为 TRACE。在找不到 Bot 的时候会输出当前缓存的列表。

https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/blob/a38141634b5594fb78bad4f6b68895ff46ba86b4/nonebot_plugin_saa/auto_select_bot.py#L128
