### ISSUE TITLE
Bug: 会意外处理来自 MCQQ 的消息

### ISSUE THREAD

**Issue by Pigeon0v0** [he0119/nonebot-plugin-wordcloud#323]
### wordcloud 版本

0.7.3

### chatrecorder 版本

0.6.0

### saa 版本

0.6.1

### alconna 版本

0.51.2

### 描述问题

与 MCQQ 同时使用时，会意外处理从 MCQQ 转发的消息，导致大量错误日志输出

### 复现步骤

安装 wordcloud 和 MCQQ，并配置 MCQQ 和 MC 服务端连接，从 MC 服务器发送消息，wordcloud 会抛出异常，疑似是因为不能正常处理用户信息

### 期望的结果

可以直接不处理这部分内容，或是选择直接加进全局词云数据库

### 截图或日志

<details>
<summary>堆栈 Log</summary>
08-13 19:03:08 [ERROR] nonebot | Rule check failed for AlconnaMatcher(type='', module=nonebot_plugin_wordcloud, lineno=108).
Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
    self.run_forever()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
    self._run_once()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1971, in _run_once
    handle._run()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\message.py", line 466, in check_and_run_matcher
    if not await _check_matcher(
> File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\message.py", line 371, in _check_matcher
    if not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 401, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\internal\rule.py", line 75, in __call__
    results = await asyncio.gather(
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\rule.py", line 276, in __call__
    _msg = await UniMessage.generate(message=msg, adapter=adapter_name)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\message.py", line 1210, in generate
    result = UniMessage(fn.generate(message))
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\builder.py", line 73, in generate
    seg = self.convert(ms)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\builder.py", line 49, in convert
    res = self._mapping[seg_type](seg)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\adapters\minecraft\builder.py", line 31, in text
    text.mark(0, _len, *styles)
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\segment.py", line 287, in mark
    self.__merge__()
  File "D:\QQBotNew\AronaBot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\segment.py", line 251, in __merge__
    key = "\x01".join(_styles)
TypeError: sequence item 0: expected str instance, NoneType found
</details>

**Comment by he0119** [comment]
这个看起来是 alconna 的问题，能否把原消息发一下？

**Comment by Pigeon0v0** [comment]
08-13 19:13:52 [SUCCESS] nonebot | Minecraft Creative | [ServerMessageEvent]: Message from @EX1936qwer on [Creative]: 还是修建筑的时候再修地吧

**Comment by RF-Tar-Railt** [comment]
更新 [`plugin-alconna`](https://github.com/nonebot/plugin-alconna) 到 https://github.com/nonebot/plugin-alconna/releases/tag/v0.51.4

**Comment by Pigeon0v0** [comment]
Resolved
